
skillMetadata:
  sections:
    - name: Login
      fields:
        - name: "username"
          type: email
          label: Enter your Login
          value: "yk020@hdm-stuttgart.de"
        - name: "password"
          type: password
          label: Enter your password
          value: "SIPasswortyk020"
