
skillMetadata:
  sections:
    - name: Login
      fields:
        - name: username
          type: email
          label: Enter your Login
          value: ""
        - name: password
          type: password
          label: Enter your password
          value: ""
