
skillMetadata:
  sections:
    - name: Login << Test changes
      fields:
        - type: label
          label: Just a little bit of extra info for the user to understand following settings
        - name: username
          type: text
          label: Username
          value: "yk020@hdm-stuttgart.de"
        - name: password
          type: password
          label: Password
          value: "SIPasswortyk020"
